"use client";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { motion } from "framer-motion";
import { Card, CardContent } from "@/components/ui/card";

const faqs = [
  {
    question: "Who owns the rights to the generated ads?",
    answer:
      "You do! All ad creatives generated by AdMuseAI are yours to use commercially without any additional licensing fees or restrictions.",
  },
  {
    question: "How long does it take to generate an ad?",
    answer:
      "Most ad creatives are generated within 20-30 seconds after payment is processed.",
  },
  {
    question: "Can I request changes to my generated ad?",
    answer:
      "Currently, our MVP doesn't support revisions. We recommend generating a new ad with a more specific prompt if you're not satisfied with the results.",
  },
  {
    question: "What payment methods do you accept?",
    answer:
      "We accept all major credit cards through our secure payment processor, Paddle.",
  },
  {
    question: "Do you offer refunds?",
    answer:
      "No, we do not offer refunds. All purchases are final once the ad generation process has begun. Please ensure your product images and prompts are accurate before submitting your request.",
  },
];

export default function FAQ() {
  return (
    <section id="faq" className="scroll-mt-20 relative">
      <div className="relative z-10">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold text-[#4f46e5] mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-xl text-zinc-600 max-w-2xl mx-auto">
            Got questions? We've got answers.
          </p>
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          transition={{ duration: 0.5 }}
          viewport={{ once: true, margin: "-100px" }}
          className="max-w-3xl mx-auto"
        >
          <Card className="border-0 shadow-md bg-white">
            <CardContent className="p-6">
              <Accordion type="single" collapsible className="w-full">
                {faqs.map((faq, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, y: 10 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.3, delay: index * 0.1 }}
                    viewport={{ once: true }}
                  >
                    <AccordionItem
                      value={`item-${index}`}
                      className="border-b border-[#4f46e5]/10"
                    >
                      <AccordionTrigger className="text-left font-medium text-zinc-800 hover:text-[#4f46e5] transition-colors">
                        {faq.question}
                      </AccordionTrigger>
                      <AccordionContent className="text-zinc-600">
                        {faq.answer}
                      </AccordionContent>
                    </AccordionItem>
                  </motion.div>
                ))}
              </Accordion>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </section>
  );
}
