import Link from "next/link";

export const metadata = {
  title: "Terms and Conditions | AdMuseAI",
  description:
    "Terms and Conditions for AdMuseAI's AI-powered ad creative generation platform.",
};

export default function TermsAndConditions() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <div className="mb-8">
        <Link
          href="/"
          className="text-indigo-600 hover:text-indigo-800 transition-colors"
        >
          ← Back to Home
        </Link>
      </div>

      <h1 className="text-3xl md:text-4xl font-bold mb-8">
        Terms and Conditions
      </h1>
      <div className="prose prose-lg max-w-none">
        <p className="text-gray-500 mb-8">
          Last updated: {new Date().toLocaleDateString()}
        </p>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">1. Introduction</h2>
          <p>
            Welcome to AdMuseAI ("Company", "we", "our", "us")! These Terms and
            Conditions ("Terms", "Terms and Conditions") govern your use of our
            website and AI-powered ad creative generation services (together or
            individually "Service") operated by AdMuseAI.
          </p>
          <p className="mt-2">
            By accessing or using the Service, you agree to be bound by these
            Terms. If you disagree with any part of the terms, then you may not
            access the Service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">2. Use of Service</h2>
          <p>
            Our Service allows you to upload images and generate AI-powered ad
            creatives. You are responsible for the content you upload to our
            Service and you confirm that:
          </p>
          <ul className="list-disc pl-6 mt-4 space-y-2">
            <li>
              You own or have the right to use any content you upload to our
              Service.
            </li>
            <li>
              Your use of the Service will not violate any rights of any third
              party, including intellectual property rights.
            </li>
            <li>
              You will not use our Service to generate content that is illegal,
              offensive, harmful, deceptive, defamatory, or otherwise
              inappropriate.
            </li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            3. Payment and Refund Policy
          </h2>
          <p>
            We charge fees for certain aspects of our Service. By using paid
            features, you agree to pay the applicable fees. All fees are
            non-refundable. Once the ad generation process has begun, all
            purchases are final.
          </p>
          <p className="mt-2">
            Payment is processed through our third-party payment processors. We
            do not store your full payment information on our servers.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            4. Intellectual Property Rights
          </h2>
          <p>
            <strong>Your Content:</strong> You retain all rights to the images
            you upload to our Service. By uploading content, you grant us a
            limited license to use, store, and process that content solely for
            the purpose of providing our Service to you.
          </p>
          <p className="mt-2">
            <strong>Generated Content:</strong> You own all rights to the ad
            creatives generated by our Service based on your inputs. You may use
            these creatives for commercial purposes without attribution to
            AdMuseAI.
          </p>
          <p className="mt-2">
            <strong>Our Content:</strong> The Service and its original content
            (excluding content provided by users), features, and functionality
            are and will remain the exclusive property of AdMuseAI and its
            licensors.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            5. Limitation of Liability
          </h2>
          <p>
            To the maximum extent permitted by applicable law, in no event shall
            AdMuseAI be liable for any indirect, punitive, incidental, special,
            consequential damages, or any damages whatsoever including, without
            limitation, damages for loss of use, data, or profits, arising out
            of or in any way connected with the use or performance of the
            Service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            6. Service Modifications
          </h2>
          <p>
            We reserve the right to modify or discontinue, temporarily or
            permanently, the Service (or any part thereof) with or without
            notice. We shall not be liable to you or to any third party for any
            modification, suspension, or discontinuance of the Service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">7. Governing Law</h2>
          <p>
            These Terms shall be governed and construed in accordance with the
            laws of [Your Jurisdiction], without regard to its conflict of law
            provisions.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">8. Changes to Terms</h2>
          <p>
            We reserve the right, at our sole discretion, to modify or replace
            these Terms at any time. If a revision is material, we will try to
            provide at least 30 days' notice prior to any new terms taking
            effect.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">9. Contact Us</h2>
          <p>
            If you have any questions about these Terms, please contact us at:
            <br />
            <a
              href="mailto:support@admuseai.com"
              className="text-indigo-600 hover:text-indigo-800"
            >
              support@admuseai.com
            </a>
          </p>
        </section>
      </div>
    </div>
  );
}
